ubsApp.sideScoreBoardConfig={
    "sideScoreBoard":{
    "templates":[
        {
            "templateId":13,
            "templateType":"sideScoreBoard",
            "bankBalanceTitle":"{{bankBalanceTitle}}",
            "cashTitle":"{{cashTitle}}",
            "debtTitle":"{{debtTitle}}",
            "withdrawTitle":"{{withdrawTitle}}",
            "transferTitle":"{{transferTitle}}",
            "payOffTitle":"{{payOffTitle}}",
            "playerNameLabel":"{{playerNameTitle}}",
            "diceValueLabel":"{{diceValueTitle}}",
            "inventoryTitle":"{{inventoryTitle}}",
            "buy":"{{buy}}",
            "reputationTitle":"{{reputationTitle}}",
            "advantageCardTitle":"{{advantageCardTitle}}",
            "convertTitle":"{{convertTitle}}",
            "quizTitle":"{{quizTitle}}",
        }
    ]
}
}