ubsApp.withdrawFromBankConfig={
    "withdrawFromBank":{
        "templates":[
            {
                "templateId":14,
                "templateType":"withdrawFromBank",
                "title":"{{withdrawFromBankTitle}}",
                "cashTitle":"{{cashTitle}}",
                "bankBalanceTitle":"{{bankBalanceTitle}}",
                "withdrawTitle":"{{withdrawTitle}}",			
                "amountToTransferTitle":"{{amountToWithdrawTitle}}",
                "cancelTitle":"{{cancelTitle}}",
                "withdraw":true,
            }
        ]
    }
}